import type { Metadata } from "next";
import {Inter, Jua} from "next/font/google";
import "./globals.css";

// Using the `Inter` font with Next.js font optimization
const inter = Inter({
  subsets: ['latin'],
  weight: '400',
});

const jua = Jua({
  subsets: ['latin'],
  weight: '400',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${jua.className}`}>
        {children}
      </body>
    </html>
  );
}
